language: php
php:
  - 5.3
  - 5.4
services:
  - redis-server
before_script: 
  - composer install
script:
  - cp config/config.json-dist config/config.json
  - ./vendor/atoum/atoum/bin/atoum -d tests/units